apiVersion: v1
kind: Service
metadata:
  name: bordspel
spec:
  selector:
    app: bordspel
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bordspel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bordspel
  template:
     metadata:
        labels:
           app: bordspel
     spec:
       containers:
       - name: api
         image: rloman/bordspel_api:latest	# Replace 'rloman' below 'api' section with your Docker hub id or prefix with the registry
         ports:
         - containerPort: 8080
         readinessProbe: 
           httpGet: 
             path: api/bordspels
             port: 8080
           initialDelaySeconds: 10 #Default 0, time before the very first check
           periodSeconds: 10 #Default 10, checks every 10 seconds
           timeoutSeconds: 2 #Default 1, the call may last at most 2 seconds
           successThreshold: 1 #Default 1, after a failure this is the minimum successful calls before the api should be considered ready (again)
           failureThreshold: 3 #Default 3, after a success this is the minim unsuccessful calls before the api should be considered failing
         livenessProbe:
           initialDelaySeconds: 8 #Default 0, time before the very first check
           exec:
             command:
               - ls
               - /app.jar
