apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynginx
  name: clusterip
  namespace: achmea
spec:
  ports:
  - name: 8082-80
    port: 8082
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx
  type: ClusterIP
