apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: achmea
spec:
  ports:
  - name: 8081-80
    nodePort: 31001
    port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx
  type: NodePort
