apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: achmea
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  restartPolicy: OnFailure
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: ubuntu-container
    image: ubuntu
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello, World on 2022-12-18T11:33+01:00!!! > /pod-data/index.html"]
