apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multipod
  name: multipod
  namespace: multipod-ns
spec:
  containers:
  - image: nginx:latest
    name: multipod-c1
    ports:
    - containerPort: 80
  - image: registry:latest
    name: multipod-c2
    ports:
    - containerPort: 5000
  restartPolicy: Always
  dnsPolicy: ClusterFirst
