apiVersion: v1
kind: Service
metadata:
  labels:
    app: loadbalancer-service
  name: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
  - name: 8081-80
    port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
