apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: clusterip
  namespace: acme
spec:
  type: ClusterIP
  ports:
  - name: 8082-80
    port: 8082
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
