apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  namespace: acme
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  restartPolicy: OnFailure
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  # this container below will end before it is tested for Readiness so this pod will be in a NotReady state although the nginx-container is available.
  # And be aware that this is a Pod, so it will NOT be rescheduled as that is the case for a Deployment
  - name: ubuntu-container
    image: ubuntu:latest
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello, World on 2022-12-18T11:33+01:00!!! > /pod-data/index.html"]
